version: '3.9'

services:
  mysql:
    container_name: goomer_mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_goomer
      MYSQL_ROOT_PASSWORD: challenge
    volumes:
      - "./src/infra/mysql/0001-initial-db-structure.sql:/docker-entrypoint-initdb.d/init.sql"

  redis:
     container_name: goomer_redis
     image: redis
     init: true
     restart: always
     command: redis-server --save 20 1 --loglevel warning
     ports:
       - "6379:6379"
