version: '3.9'

services:
  mysql:
    container_name: goomer_mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_goomer
      MYSQL_ROOT_PASSWORD: challenge
